name: Slack Issue Notification
'on':
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SE_TOOL_REQUESTS_WEBHOOK }}
          SLACK_CHANNEL: se-tool-requests
          SLACK_COLOR: good
          SLACK_MESSAGE: |
            ${{ github.event.issue.title }}
            ${{ github.event.issue.url }}
          SLACK_TITLE: 'Community Step Template Library Issue Created'
          SLACK_USERNAME: 'Slack Notification Workflow'
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
